require "rails"

# configure these defaults based on Your needs :
JS_FILES_AND_DIRS = ['app/assets/js_to_compile/lang','app/assets/js_to_compile/VISH.js', 'app/assets/js_to_compile/libs','app/assets/js_to_compile/VISH.Utils.js', 'app/assets/js_to_compile/VISH.Editor.js', 'app/assets/js_to_compile/VISH.Editor.Video.js', 'app/assets/js_to_compile/VISH.Editor.Image.js', 'app/assets/js_to_compile/VISH.Editor.Object.js', 'app/assets/js_to_compile/VISH.Samples.js', 'app/assets/js_to_compile/VISH.Samples.API.js', 'app/assets/js_to_compile', 'app/assets/js_to_compile/mods/fc']

COMPILER_JAR_PATH = "lib/java/build/compiler.jar" # adjust the jar path !
COMPILER_DOWNLOAD_URI = 'http://closure-compiler.googlecode.com/files/compiler-latest.zip'

#
# a javascript compile rake task (uses google's closure compiler).
#
# @see http://code.google.com/closure/compiler/
#
namespace :vish_editor do
    
  task :prepare do
    system "rm -rf app/assets/images"
    system "rm -rf app/assets/js_to_compile"
    system "rm -rf app/assets/stylesheets"
    system "rm -rf app/assets/javascripts/vishEditor.js"
    system "rm -rf app/assets/javascripts/vishEditor.min.js"
    system "mkdir -p app/assets"
    system "cp -r ../images/ app/assets/images/"
    system "cp -r ../js/ app/assets/js_to_compile/"
    system "cp -r ../stylesheets/ app/assets/stylesheets/"
    #replace path /images and /stylesheets by /assets    
    system "sed -i 's/vishEditor\\\/images/assets/g' app/assets/stylesheets/*/*css"
    system "sed -i 's/vishEditor\\\/images/assets/g' app/assets/js_to_compile/VISH.js"
    system "sed -i 's/vishEditor\\\/stylesheets/assets/g' app/assets/js_to_compile/VISH.js"
  end

  task :clean do
    system "rm -rf app/assets/js_to_compile"
  end

  task :compile do 
    Rake::Task["vish_editor:prepare"].invoke
    js_files = []
    JS_FILES_AND_DIRS.each do |dir|
      if dir =~ /js$/
        js_files << dir
      else
        js_files.concat(Dir[ File.join(dir, "*.js") ].sort)
      end
    end
    js_files.uniq!
    puts "matched #{js_files.size} .js file(s)"
    compile_js(js_files)
    Rake::Task["vish_editor:clean"].invoke
  end

  desc "downloads (and extracts) the latest closure compiler.jar into COMPILER_JAR_PATH path (#{COMPILER_JAR_PATH})"
  task :download_jar do
    require 'uri'; require 'net/http'; require 'tempfile'; require 'open-uri'
    puts "downloading compiler jar from: #{COMPILER_DOWNLOAD_URI}"
   
    FileUtils.mkdir_p("compiler") 
    writeOut = open("compiler/compiler-latest.zip", "wb")
    writeOut.write(open(COMPILER_DOWNLOAD_URI).read)
    writeOut.close
   
    extract_path = File.dirname(compiler_jar_path)
    
    FileUtils.mkdir_p(extract_path)
    # -u  update files, create if necessary :
    system "unzip -u compiler/compiler-latest.zip -d #{extract_path}"
  end

  #========================================================================

  def compile_js(files)
    unless File.exist?(compiler_jar_path)
      Rake::Task["vish_editor:download_jar"].invoke
    end
    unless File.exist?(compiler_jar_path)
      puts "#{compiler_jar_path} not found !"
      raise "try to run `rake vish_editor:download_jar` manually to download the compiler jar"
    end

    files = [ files ] unless files.is_a?(Array)

    compiler_options = {}
    compiler_options['--js'] = files.join(' ')
    compiler_options['--compilation_level'] = 'SIMPLE_OPTIMIZATIONS'
    compiler_options['--js_output_file'] = "vishEditor.min.js"
    compiler_options['--warning_level'] = 'QUIET'
    compiler_options2 = {}
    compiler_options2['--js'] = files.join(' ')
    compiler_options2['--compilation_level'] = 'WHITESPACE_ONLY'
    compiler_options2['--formatting'] = 'PRETTY_PRINT'
    compiler_options2['--js_output_file'] = "vishEditor.js"
    compiler_options2['--warning_level'] = 'QUIET'
    
    files.each do |file|
      puts " > #{file}"
    end
    
    puts ""
    puts "----------------------------------------------------"
    puts "compiling ..."

   
    system "java -jar #{compiler_jar_path} #{compiler_options.to_a.join(' ')}"
    system "java -jar #{compiler_jar_path} #{compiler_options2.to_a.join(' ')}"
    puts "DONE"
    puts "----------------------------------------------------"
    puts "compiled #{files.size} javascript file(s) into vishEditor.js and vishEditor.min.js"
    puts ""
    system "mkdir -p app/assets/javascripts"
    system "mv vishEditor.js app/assets/javascripts/vishEditor.js"
    system "mv vishEditor.min.js app/assets/javascripts/vishEditor.min.js"

  end

  def compiler_jar_path
    ENV['COMPILER_JAR_PATH'].presence || COMPILER_JAR_PATH
  end

end
